### ISSUE TITLE
Bumping versions often stalls release pipeline

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/.github#116]
#### Describe the bug
When the node.js release pipeline bumps the package version often times GH stalls the CI runs, meaning the release pipeline is completely stuck.  See https://github.com/asyncapi/modelina/pull/561

Because of the changes introduced in the version bump `chore(release): ...` we dont need to run all the workflows and in theory skip them.

**Comment by derberg** [comment]
damn, forgot about one thing, `skip ci` skips testing, but it is required on repo level...so these checks will be blocking merge 🤦🏼

**Comment by derberg** [comment]
some info here https://github.community/t/github-pull-request-is-waiting-for-required-status-checks-even-with-ci-skip-in-commit-message/827

I added a comment as well

**Comment by KhudaDad414** [comment]
Why don't we trust the bot and skip testing in case the author is `asyncapi-bot` [here](https://github.com/asyncapi/.github/blob/master/.github/workflows/if-nodejs-pr-testing.yml#L12)? any side effects?

**Comment by derberg** [comment]
@KhudaDad414 oh man 🤯 I honestly did not take it into account 🤦🏼 
I was always declining it as `asyncapi-bot` cannot always be trusted, because sometimes `asyncapi-bot` sends PRs that are bump of package version, so tests must run to make sure that for example a bump of parser in generator will not break generator.

But we can also figure it out from the PR title I guess, just like we do it [here](https://github.com/asyncapi/generator/blob/master/.github/workflows/update-docs-on-docs-commits.yml#L26) 🤔 

so we could always trust allcontributors bot and asyncapi-bot in certain situations...

**Comment by derberg** [comment]
@KhudaDad414 it didn't work. In all 59 repos (if we had branch protection set properly everywhere) the update of worklows failed because the tests were not triggered, so branch protection was not satisfied. Tests were not triggered because the test workflow was properly skipped because of new condition. So your idea worked but partially because workflow is skipped, jobs are not triggered, so PRs hang like here https://github.com/asyncapi/modelina/pull/614

Can you try closing these PRs and make a followup PR and move `if` form job to steps. It is not as grand as initial idea but still improvement that we need imho

**Comment by KhudaDad414** [comment]
@derberg I don't have enough permission to close the PRs.

**Comment by derberg** [comment]
@KhudaDad414 no worries. I'll close them

**Comment by KhudaDad414** [comment]
Left a comment and it was already merged in the following repos:
```
dotnet-nats-template
go-watermill-template
vs-asyncapi-preview
shape-up-process
event-gateway
community
template-for-go-projects
parser-api
glee
create-glee-app
brand
infra
java-template
```
It was approved but wasn't merged for some weird reason in `asyncapi-php-template` :|

**Comment by derberg** [comment]
@KhudaDad414 I followedup in all PRs and closed them.

**Comment by derberg** [comment]
@KhudaDad414 I triggered merge of your followup, next we should merge https://github.com/asyncapi/.github/pull/131 as the change in the bump workflow that you did in pervious PR was not replicated, so in my PR for TSC slack I made an adjustment that will trigger replication again

**Comment by derberg** [comment]
@jonaslagoni I recommend you apply the same conditions that @KhudaDad414 did in the last PR in your custom black-box testing in modelina, to skip tests running in PRs like adding someone to list of contributors

**Comment by jonaslagoni** [comment]
> @jonaslagoni I recommend you apply the same conditions that @KhudaDad414 did in the last PR in your custom black-box testing in modelina, to skip tests running in PRs like adding someone to list of contributors

Will do 👍
