### ISSUE TITLE
Auto-merge workflow allows unreviewed code to be published

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/.github#119]
#### Describe the bug
Because the workflow does not care about what changes and who did the change, any maintainer can avoid the 1 people review process, by pushing code to the auto-update PRs. 

#### How to Reproduce
Proof: https://github.com/asyncapi/ts-nats-template/pull/413

#### Expected behavior
The expected behavior would be that the bot does not approve PR's where collaborators have pushed changes to.

**Comment by KhudaDad414** [comment]
AFAIK bots push their changes in one commit. Does merging only if there is only one commit in the PR solves the issues? I went through the GitHub API and it seems like the easiest solution.

**Comment by derberg** [comment]
@KhudaDad414 sometimes there might be an update done, merge of master -> https://github.com/asyncapi/.github/blob/master/.github/workflows/autoupdate.yml so there can be 2 commits. So I think the only option is to really check the `author` of the pull request update, and if it is not a bot, then we should revoke GH Action bot approval

**Comment by KhudaDad414** [comment]
@derberg What about checking the authors of commits before merging?
With checking the `author` of the pull request update, how can we guarantee that the merging doesn't happen BEFORE the `pull request update` revokes the approval?

**Comment by derberg** [comment]
🤔 

so what we know is that because of this setting:
![Screenshot 2022-01-10 at 13 05 53](https://user-images.githubusercontent.com/6995927/148763436-8d578e4f-d4b9-46f2-b7f8-b10194a14df7.png)

Changes introduced by @jonaslagoni caused dismiss of approval
![Screenshot 2022-01-10 at 13 05 28](https://user-images.githubusercontent.com/6995927/148763375-c4e3e625-5fbd-4d3f-9ef0-cb6ccd8619d2.png)

But PR got approved again because we are checking now not the "event author" but logging of the user that created the PR -> https://github.com/asyncapi/ts-nats-template/blob/master/.github/workflows/automerge.yml#L24

I changed it just recently, but.....omg I don't remember why...

the only idea that comes to my mind is that I did it because [this](https://github.com/asyncapi/ts-nats-template/blob/master/.github/workflows/autoupdate.yml) workflow was not working...why? because PR created by AsyncAPI bot was updated by GitHub Actions bot and the approval was dismissed and merging could not be done. So maybe I was just stupid and instead of introducing checking of the PR creator login, we should just change [this](https://github.com/asyncapi/ts-nats-template/blob/master/.github/workflows/autoupdate.yml#L24) line to `GH_TOKEN` to perform autoupdate (merge of master to PR) with AsyncAPI bot?

I had a too-long break, and have holes in my memory 😆
