### ISSUE TITLE
Updates to Issue templates 🛠

### ISSUE THREAD

**Issue by tamalCodes** [asyncapi/.github#212]
### Reason/Context

I  am suggesting to update the Issue templates , currently we are using `.md` files instead of the brand new issue forms with `.yml` files.

### Why to update it ? 

- The `.yml` based issue templates makes it more easier to organize, ask your questions, add screenshots and choose other options as necessary
- Plus, we can add "custom" labels to the issue template which makes it more organized than having a bot/user do it.

### Relevant screenshots

![image](https://user-images.githubusercontent.com/72851613/192107388-3b5564d1-4efc-4e05-8fd8-ecb271136a77.png)

![image](https://user-images.githubusercontent.com/72851613/193424759-6ff15f6b-c43a-4de2-bcab-931bc9e06ec3.png)

### Am i willing to work on it ? 

Yes, i will be glad to help an Opensource project grow more !

**Comment by derberg** [comment]
I moved the issue as the sources of templates, and PR has to be opened here in `.github` repo -> https://github.com/asyncapi/.github/tree/master/.github/ISSUE_TEMPLATE

@IAmTamal since you reported the issue and proposed a solution you can open a PR, unless you are ok someone else is doing it.

I suggest we do it in `bug` and `enhancement` templates
