### ISSUE TITLE
Add test coverage check to all projects

### ISSUE THREAD

**Issue by derberg** [asyncapi/.github#30]
#### Reason/Context
As mentioned [here](https://github.com/asyncapi/asyncapi/issues/423#issuecomment-737745862) we should start test coverage monitoring.

#### Description
- setup test coverage, best with some SaaS that is free for open source
- add badges to repos (optional)
- make sure test coverage is a check on a PR level. It is a mandatory check. PR should be blocked from merging if tests coverage decreases with given PR

**Comment by jonaslagoni** [comment]
We have been running Coveralls in [Modelina](https://github.com/asyncapi/modelina) for some time now where it:
- Share how the coverage is affected in PR's
- Block a PR if it falls below certain thresholds

We are using the following GitHub action workflow: https://github.com/asyncapi/modelina/blob/3ffe75f5799518b1b8ffbf7abb2c28bdaa6b7e23/.github/workflows/coverall.yml

Important note the event `pull_request_target` cannot be used here since we need to trigger the bot on their `pull_request` and using their branch. Otherwise it cannot detect the coverage changes.

**Comment by jonaslagoni** [comment]
I have noticed something annoying with coverall, sometimes, it cannot complete its CI run for some random reason. Almost like it cant generate the coverage report, which usually happens when the commits have nothing to do with tests or code. I'll see if I can catch it again
