### ISSUE TITLE
Synchronize general documentation

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/.github#40]
#### Reason/Context
The files CODE_OF_CONDUCT.md, CONTRIBUTING.md, FUNDING.yml, SECURITY.md, and SUPPORT.md should IMO be synchronized to the organization's repositories to provide a coherent documentation experience.

#### Description

As @derberg suggested on Slack there are two solutions to this.
1. Synchronzie the documents
2. Repository "owners" create their own wrappers to files such as CONTRIBUTING.md and simply reference this repository.

There are pros and cons for both solutions, so what fits best?

I assume it is somewhat related to https://github.com/asyncapi/.github/issues/38

**Comment by derberg** [comment]
this is very much needed, people still expect CONTRIBUTING file as part of the repo as a file on the root. Habits 🤷🏼

**Comment by derberg** [comment]
I think it is going to happen pretty soon 😄 stay tuned

**Comment by derberg** [comment]
@Relequestual 

1 - yup, we do it with the workflow files already. Just that instead of markdown comment it should be HTML comment that is visible only in a source file IMHO
2 - yup, this is how will it work, you basically provide a list of files
3 - yes yes yes, or no 😄 I was thinking about it, like a "topic" that you set on a repo to say `you shall not pass`, but on the other things, I was thinking about an approach that actually the contribution guide anyway must be as generic as possible, and should be copied everywhere and then per repo you just need to have "contribution guide extensions", like additional files, repo specific 🤔
